<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $statements = [
            'CREATE TABLE IF NOT EXISTS `AC_FEUIL` (
  `ACCLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `DATEACTE` date DEFAULT NULL,
  `TYPEACTE` int DEFAULT \'0\',
  `DESACTE` varchar(150) DEFAULT NULL,
  `MONTACT_HT` decimal(24,6) DEFAULT \'0.000000\',
  `MONTACT` decimal(24,6) DEFAULT \'0.000000\',
  `PARTIPM` decimal(24,6) DEFAULT \'0.000000\',
  `PARTPARTICIPANT` decimal(24,6) DEFAULT \'0.000000\',
  `FECLEUNIK` int DEFAULT \'0\',
  `TAUX2` smallint DEFAULT \'0\',
  `IDActe` decimal(19,0) DEFAULT \'0\',
  `Forfait` decimal(24,6) DEFAULT \'0.000000\',
  `Plafond` decimal(24,6) DEFAULT \'0.000000\',
  PRIMARY KEY (`ACCLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `ADHERANT` (
  `IDADHERANT` bigint NOT NULL AUTO_INCREMENT,
  `CODEADHERANT` varchar(50) DEFAULT NULL,
  `ADHERANT` varchar(40) DEFAULT NULL,
  `Adresse` text,
  `TEL` varchar(10) DEFAULT NULL,
  `FAX` varchar(10) DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `NBR_PARTICIPANT` int DEFAULT \'0\',
  `CONTACT` varchar(50) DEFAULT NULL,
  `FONCTION1` varchar(30) DEFAULT NULL,
  `TELContact` varchar(10) DEFAULT NULL,
  `CONTACT2` varchar(30) DEFAULT NULL,
  `FONCTION2` varchar(30) DEFAULT NULL,
  `TEL2` varchar(10) DEFAULT NULL,
  `ENCOURS` decimal(24,6) DEFAULT \'0.000000\',
  `ENCOURS2` decimal(24,6) DEFAULT \'0.000000\',
  `ADACTIF` int DEFAULT \'0\',
  `COMPTE_COMPTABLE` varchar(8) DEFAULT NULL,
  `NB_COTISE` int DEFAULT \'0\',
  `MT_COTISE_EMPLOYEUR` decimal(24,6) DEFAULT \'0.000000\',
  `MT_COTISE_STAFF` decimal(24,6) DEFAULT \'0.000000\',
  `Email_Contact` varchar(256) DEFAULT NULL,
  `IDFDA` decimal(19,0) DEFAULT \'0\',
  PRIMARY KEY (`IDADHERANT`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `BANQUE` (
  `IDBANQUE` bigint NOT NULL AUTO_INCREMENT,
  `SIGLE` varchar(50) DEFAULT NULL,
  `DESIGNATION` varchar(100) DEFAULT NULL,
  `COMPTE_BANCAIRE` varchar(50) DEFAULT NULL,
  `COMPTE_COMPTABLE` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`IDBANQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `CMDPHARM` (
  `CMCLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `NUMCOMMANDE` varchar(20) DEFAULT NULL,
  `DATECMD` date DEFAULT NULL,
  `NBARTICLES` smallint DEFAULT \'0\',
  `PHCLEUNIK` int DEFAULT \'0\',
  `NOMPHARMACIE` varchar(60) DEFAULT NULL,
  `PACLEUNIK` int DEFAULT \'0\',
  `ADCLEUNIK` int DEFAULT \'0\',
  `NOMPARTICIPANT` varchar(50) DEFAULT NULL,
  `NumMalade` int DEFAULT \'0\',
  `NOMMALADE` varchar(50) DEFAULT NULL,
  `DEJASAISIE` smallint DEFAULT \'0\',
  `MEDECIN` varchar(40) DEFAULT NULL,
  `DATE_ORD` date DEFAULT NULL,
  `TYPE_COMMANDE` int DEFAULT \'0\',
  `FACLEUNIK` int DEFAULT \'0\',
  `NUMERO_FACTURE` varchar(20) DEFAULT NULL,
  `FACTURE` int DEFAULT \'0\',
  `OBSERVATION` text,
  `F1CLEUNIK` int DEFAULT \'0\',
  `IDDECOMPTE_PAR` int DEFAULT \'0\',
  `heurecmd` time DEFAULT NULL,
  `Date_Prestation` date DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `MONTANT` decimal(24,6) DEFAULT \'0.000000\',
  `PARTIPM` decimal(24,6) DEFAULT \'0.000000\',
  `PARTPARTICIPANT` decimal(24,6) DEFAULT \'0.000000\',
  `IDSpecialite` decimal(19,0) DEFAULT \'0\',
  `PRCLEUNIK` int DEFAULT \'0\',
  `NUMCMDPHARM` varchar(20) DEFAULT NULL,
  `MALADEBIS` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CMCLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `CONGES` (
  `IDCONGES` bigint NOT NULL AUTO_INCREMENT,
  `IDPARTICIPANT` decimal(19,0) DEFAULT NULL,
  `IDSite` decimal(19,0) DEFAULT NULL,
  `IDClient` decimal(19,0) DEFAULT NULL,
  `MOIS` int DEFAULT NULL,
  `ANNEE` int DEFAULT NULL,
  `IDAdherant` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`IDCONGES`),
  UNIQUE KEY `IDPARTICIPANT` (`IDPARTICIPANT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `COT_PAR` (
  `C0CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `MOISCOTISE` smallint DEFAULT \'0\',
  `ANNEECOTISE` int DEFAULT \'0\',
  `DATECOTISE` date DEFAULT NULL,
  `MTCOTISE` decimal(24,6) DEFAULT \'0.000000\',
  `MTBASE` decimal(24,6) DEFAULT \'0.000000\',
  `PACLEUNIK` int DEFAULT \'0\',
  `NBMOIS` int DEFAULT \'0\',
  `COCLEUNIK` int DEFAULT \'0\',
  PRIMARY KEY (`C0CLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=9984918 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `COTISE` (
  `COCLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `ADCLEUNIK` int DEFAULT \'0\',
  `MOISCOTISE` smallint DEFAULT \'0\',
  `ANNEECOTISE` int DEFAULT \'0\',
  `DATECOTISE` date DEFAULT NULL,
  `MTCOTISESAL` decimal(24,6) DEFAULT \'0.000000\',
  `MTCOTISE` decimal(24,6) DEFAULT \'0.000000\',
  `MTREGLE` decimal(24,6) DEFAULT \'0.000000\',
  `NBPLANCHER` int DEFAULT \'0\',
  `NBPLAFOND` int DEFAULT \'0\',
  `NBTOTAL` int DEFAULT \'0\',
  `NBINTERMED` int DEFAULT \'0\',
  `MTPLAFOND` decimal(24,6) DEFAULT \'0.000000\',
  `MTPLANCHER` decimal(24,6) DEFAULT \'0.000000\',
  `TAUX` double DEFAULT \'0\',
  `MTINTERMED` decimal(24,6) DEFAULT \'0.000000\',
  `NBMOIS` int DEFAULT \'0\',
  `MOISFINCOTSE` smallint DEFAULT \'0\',
  `ANNEEFINCOTISE` int DEFAULT \'0\',
  `TYPECOTISE` smallint DEFAULT \'0\',
  `COMMENTAIRE` text,
  PRIMARY KEY (`COCLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `DECOMPTE` (
  `D0CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `PACLEUNIK` int DEFAULT \'0\',
  `DATEACTE` date DEFAULT NULL,
  `DESACTE` varchar(150) DEFAULT NULL,
  `TOTAL` decimal(24,6) DEFAULT \'0.000000\',
  `TOTALIPM` decimal(24,6) DEFAULT \'0.000000\',
  `TOTALPART` decimal(24,6) DEFAULT \'0.000000\',
  `ADCLEUNIK` int DEFAULT \'0\',
  `PRCLEUNIK` int DEFAULT \'0\',
  `PHCLEUNIK` int DEFAULT \'0\',
  `AVOIR` int DEFAULT \'0\',
  `NUMFEUILLE` int DEFAULT \'0\',
  `NUMCOMMANDE` varchar(20) DEFAULT NULL,
  `NUMERO_FACTURE` varchar(20) DEFAULT NULL,
  `OBSERVATION` text,
  `S0CLEUNIK` int DEFAULT \'0\',
  `DATEPREST` date DEFAULT NULL,
  `MATRICULE_PARTICIPANT` varchar(20) DEFAULT NULL,
  `IDSITES` int DEFAULT \'0\',
  PRIMARY KEY (`D0CLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `DEPENSE` (
  `IDDEPENSE` bigint NOT NULL AUTO_INCREMENT,
  `IDRUBDEP` decimal(19,0) DEFAULT NULL,
  `Date` date DEFAULT NULL,
  `Libelle` text,
  `MONTANT` decimal(24,6) DEFAULT NULL,
  `Mode` smallint DEFAULT NULL,
  `IDBANQUE` decimal(19,0) DEFAULT NULL,
  `Reference` varchar(50) DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT NULL,
  `Numfeuille` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDDEPENSE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `DOC_EXTERNES` (
  `IDFDA` decimal(19,0) DEFAULT NULL,
  `IDDOC_EXTERNES` bigint NOT NULL AUTO_INCREMENT,
  `DOCUMENT` longblob,
  `NOM_DOCUMENT` varchar(100) DEFAULT NULL,
  `Libelle_Document` varchar(50) DEFAULT NULL,
  `IDTYPE_PIECE` decimal(19,0) DEFAULT NULL,
  `IDUtilisateur` decimal(19,0) DEFAULT NULL,
  `Niveau` int DEFAULT NULL,
  `IDFDD` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`IDDOC_EXTERNES`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `DOC_PARTICIPANT` (
  `IDDOC_PARTICIPANT` bigint NOT NULL AUTO_INCREMENT,
  `DOCUMENT` longblob,
  `IDPARTICIPANT` decimal(19,0) DEFAULT NULL,
  `NOM_DOCUMENT` varchar(100) DEFAULT NULL,
  `Libelle_Document` varchar(50) DEFAULT NULL,
  `IDTYPE_PIECE` decimal(19,0) DEFAULT NULL,
  `IDUtilisateur` decimal(19,0) DEFAULT NULL,
  `Niveau` int DEFAULT NULL,
  PRIMARY KEY (`IDDOC_PARTICIPANT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `FACT_ADH` (
  `F1CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `NUM_FACTURE_ADH` varchar(20) DEFAULT NULL,
  `DATE_FACTURE` date DEFAULT NULL,
  `MOIS` smallint DEFAULT \'0\',
  `ANNEE` smallint DEFAULT \'0\',
  `MONTANT_FACTURE` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_REGLE` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_RESTANT` decimal(24,6) DEFAULT \'0.000000\',
  `ADCLEUNIK` int DEFAULT \'0\',
  `NB_COTISE` int DEFAULT \'0\',
  `MONTANT_PRATICIEN` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_PHARMACIE` varchar(50) DEFAULT NULL,
  `MONTANT_COTISATION` decimal(24,6) DEFAULT \'0.000000\',
  `Date_saisie` date DEFAULT NULL,
  `Heure_Saisie` time DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `MOISANNEE` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`F1CLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `FACT_PHA` (
  `FACLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `NUMERO_FACTURE` varchar(20) DEFAULT NULL,
  `DATE_FACTURE` date DEFAULT NULL,
  `MONTANT_FACTURE` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_REGLE` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_RESTANT` decimal(24,6) DEFAULT \'0.000000\',
  `BON_A_PAYER` int DEFAULT \'0\',
  `DATE_ECHEANCE` date DEFAULT NULL,
  `PHCLEUNIK` int DEFAULT \'0\',
  `DATEDEB` date DEFAULT NULL,
  `DATE_FIN` date DEFAULT NULL,
  `MONTANT_IPM` decimal(24,6) DEFAULT \'0.000000\',
  `Date_saisie` date DEFAULT NULL,
  `heure` time DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `IDTRCHEQUE` decimal(19,0) DEFAULT \'0\',
  PRIMARY KEY (`FACLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `FACT_PRA` (
  `F0CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `NUMERO_FACTURE` varchar(20) DEFAULT NULL,
  `DATE_FACTURE` date DEFAULT NULL,
  `MONTANT_FACTURE` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_REGLE` decimal(24,6) DEFAULT \'0.000000\',
  `MONTANT_RESTANT` decimal(24,6) DEFAULT \'0.000000\',
  `BON_A_PAYER` int DEFAULT \'0\',
  `DATE_ECHEANCE` date DEFAULT NULL,
  `DATEDEB` date DEFAULT NULL,
  `DATE_FIN` date DEFAULT NULL,
  `PRCLEUNIK` int DEFAULT \'0\',
  `MONTANT_IPM` decimal(24,6) DEFAULT \'0.000000\',
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `Date_saisie` date DEFAULT NULL,
  `heure` time DEFAULT NULL,
  `IDTRCHEQUE` decimal(19,0) DEFAULT \'0\',
  PRIMARY KEY (`F0CLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `FDA` (
  `IDFDA` bigint NOT NULL AUTO_INCREMENT,
  `Date_demande` date DEFAULT NULL,
  `Date_validation` date DEFAULT NULL,
  `idvalideur` int DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT NULL,
  `Responsable` varchar(100) DEFAULT NULL,
  `civilite` smallint DEFAULT NULL,
  `Forme_Juridique` varchar(50) DEFAULT NULL,
  `Denomination_Sociale` varchar(100) DEFAULT NULL,
  `Nom_Commercial` varchar(100) DEFAULT NULL,
  `Adresse` text,
  `TEL` varchar(10) DEFAULT NULL,
  `FAX` varchar(10) DEFAULT NULL,
  `NINEA` varchar(50) DEFAULT NULL,
  `REGCOM` varchar(50) DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `Effectif` int DEFAULT NULL,
  `Nouvelle_Creation` bit(1) DEFAULT NULL,
  `Complement_Adherant` bit(1) DEFAULT NULL,
  `Liste_Adherant` text,
  `Nomprecedent` varchar(100) DEFAULT NULL,
  `Reference` varchar(20) DEFAULT NULL,
  `Statut_demande` int DEFAULT NULL,
  `Rejetee` bit(1) DEFAULT NULL,
  `Areprendre` bit(1) DEFAULT NULL,
  `Areporter` bit(1) DEFAULT NULL,
  `Validee` bit(1) DEFAULT NULL,
  `Memo_Superviseur` text,
  `Memo_Validation` text,
  `Decision_Superviseur` bit(1) DEFAULT NULL,
  `Decision_DFC` bit(1) DEFAULT NULL,
  `date_envoi` date DEFAULT NULL,
  `heure_envoi` time DEFAULT NULL,
  `date_verif` date DEFAULT NULL,
  `heure_verif` time DEFAULT NULL,
  `heure__validation` time DEFAULT NULL,
  `idverificateur` int DEFAULT NULL,
  PRIMARY KEY (`IDFDA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `FDD` (
  `IDFDD` bigint NOT NULL AUTO_INCREMENT,
  `Date_demande` date DEFAULT NULL,
  `Date_validation` date DEFAULT NULL,
  `idvalideur` int DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT NULL,
  `Responsable` varchar(100) DEFAULT NULL,
  `civilite` smallint DEFAULT NULL,
  `Forme_Juridique` varchar(50) DEFAULT NULL,
  `Denomination_Sociale` varchar(100) DEFAULT NULL,
  `Nom_Commercial` varchar(100) DEFAULT NULL,
  `Adresse` text,
  `TEL` varchar(10) DEFAULT NULL,
  `FAX` varchar(10) DEFAULT NULL,
  `NINEA` varchar(50) DEFAULT NULL,
  `REGCOM` varchar(50) DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `Effectif` int DEFAULT NULL,
  `Nouvelle_Creation` bit(1) DEFAULT NULL,
  `Complement_Adherant` bit(1) DEFAULT NULL,
  `Liste_Adherant` text,
  `Nomprecedent` varchar(100) DEFAULT NULL,
  `Reference` varchar(20) DEFAULT NULL,
  `Statut_demande` int DEFAULT NULL,
  `Rejetee` bit(1) DEFAULT NULL,
  `Areprendre` bit(1) DEFAULT NULL,
  `Areporter` bit(1) DEFAULT NULL,
  `Validee` bit(1) DEFAULT NULL,
  `Memo_Superviseur` text,
  `Memo_Validation` text,
  `Decision_Superviseur` bit(1) DEFAULT NULL,
  `Decision_DFC` bit(1) DEFAULT NULL,
  `date_envoi` date DEFAULT NULL,
  `heure_envoi` time DEFAULT NULL,
  `date_verif` date DEFAULT NULL,
  `heure_verif` time DEFAULT NULL,
  `heure__validation` time DEFAULT NULL,
  `idverificateur` int DEFAULT NULL,
  `IDSpecialite` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`IDFDD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `FEUIL_MA` (
  `FECLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `NUMFEUILLE` decimal(19,0) DEFAULT \'0\',
  `PACLEUNIK` int DEFAULT \'0\',
  `ADCLEUNIK` int DEFAULT \'0\',
  `NOMPARTICIPANT` varchar(50) DEFAULT NULL,
  `NumMalade` int DEFAULT \'0\',
  `NOMMALADE` varchar(50) DEFAULT NULL,
  `TypeMalade` int DEFAULT \'0\',
  `DateFeuille` date DEFAULT NULL,
  `PRCLEUNIK` int DEFAULT \'0\',
  `NOMPRATICIEN` varchar(50) DEFAULT NULL,
  `TYPE_FEUILLE` int DEFAULT \'0\',
  `F0CLEUNIK` int DEFAULT \'0\',
  `NUMERO_FACTURE` varchar(20) DEFAULT NULL,
  `FACTURE` int DEFAULT \'0\',
  `OBSERVATION` text,
  `F1CLEUNIK` int DEFAULT \'0\',
  `IDDECOMPTE_PAR` int DEFAULT \'0\',
  `Montant_Pansement` decimal(24,6) DEFAULT \'0.000000\',
  `DATE_ORD` date DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `IDSpecialite` decimal(19,0) DEFAULT \'0\',
  `Date_Prestation` date DEFAULT NULL,
  `Heure_Saisie` time DEFAULT NULL,
  `MONTANT` decimal(24,6) DEFAULT \'0.000000\',
  `PARTIPM` decimal(24,6) DEFAULT \'0.000000\',
  `PARTPARTICIPANT` decimal(24,6) DEFAULT \'0.000000\',
  `Numero_feuille` varchar(20) DEFAULT NULL,
  `MALADEBIS` varchar(50) DEFAULT NULL,
  `LG` bit(1) DEFAULT b\'0\',
  PRIMARY KEY (`FECLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `HISTORIQUE` (
  `IDHISTORIQUE` bigint NOT NULL AUTO_INCREMENT,
  `IDPARTICIPANT` decimal(19,0) DEFAULT NULL,
  `Date_Affectation` date DEFAULT NULL,
  `Date_Fin_Affectation` date DEFAULT NULL,
  `IDClient` decimal(19,0) DEFAULT NULL,
  `IDSite` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`IDHISTORIQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `LIGCMD` (
  `LICLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `DESIGNATION` varchar(20) DEFAULT NULL,
  `Quantite` smallint DEFAULT \'0\',
  `PrixUnitaire` decimal(24,6) DEFAULT \'0.000000\',
  `TAUXLIG` double DEFAULT \'0\',
  `PARTIPM` decimal(24,6) DEFAULT \'0.000000\',
  `PARTPARTICIPANT` decimal(24,6) DEFAULT \'0.000000\',
  `CMCLEUNIK` int DEFAULT \'0\',
  `MONTANT` decimal(24,6) DEFAULT \'0.000000\',
  `Date` date DEFAULT NULL,
  PRIMARY KEY (`LICLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `NUMEROTATION` (
  `IDNUMEROTATION` bigint NOT NULL AUTO_INCREMENT,
  `DERNUM_FDA` int DEFAULT NULL,
  `DERNUM_FDD` int DEFAULT NULL,
  PRIMARY KEY (`IDNUMEROTATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `OPERATEUR` (
  `IDOPERATEUR` bigint NOT NULL AUTO_INCREMENT,
  `CODEOPERATEUR` varchar(50) DEFAULT NULL,
  `Password` varchar(50) DEFAULT NULL,
  `Nom` varchar(50) DEFAULT NULL,
  `Prenom` varchar(50) DEFAULT NULL,
  `Priorite` int DEFAULT NULL,
  `NOMOPERATEUR` varchar(50) DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `Photo` longblob,
  `Clï¿½TOTP` varchar(16) DEFAULT NULL,
  `Enveille` bit(1) DEFAULT NULL,
  `Saisie_FDA` bit(1) DEFAULT NULL,
  `Verif_FDA` bit(1) DEFAULT NULL,
  `Valide_FDA` bit(1) DEFAULT NULL,
  `Poste` varchar(50) DEFAULT NULL,
  `Direction` varchar(50) DEFAULT NULL,
  `Service` varchar(50) DEFAULT NULL,
  `saisieparam` bit(1) DEFAULT NULL,
  `saisiepharmacie` bit(1) DEFAULT NULL,
  `saisiepraticien` bit(1) DEFAULT NULL,
  `SaisieComptable` bit(1) DEFAULT NULL,
  `SaisieCotisation` bit(1) DEFAULT NULL,
  PRIMARY KEY (`IDOPERATEUR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `PARAM` (
  `IDPARAM` bigint NOT NULL AUTO_INCREMENT,
  `User` varchar(50) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  `serveursmtp` varchar(50) DEFAULT NULL,
  `Numerodeport` int DEFAULT NULL,
  `ModeAsynchrone` smallint DEFAULT NULL,
  `OptionSecurite` smallint DEFAULT NULL,
  `ModeEnvoi` smallint DEFAULT NULL,
  `DERNUM` int DEFAULT NULL,
  `SAS` varchar(50) DEFAULT NULL,
  `EMAIL` varchar(256) DEFAULT NULL,
  `EMAIL_ADMINISTRATEUR` varchar(128) DEFAULT NULL,
  `EMAIL_DEMANDEUR` varchar(128) DEFAULT NULL,
  `ServeurBDD` varchar(50) DEFAULT NULL,
  `NomBDD` varchar(50) DEFAULT NULL,
  `UserBDD` varchar(50) DEFAULT NULL,
  `PasswordBDD` varchar(50) DEFAULT NULL,
  `LDAP` bit(1) DEFAULT NULL,
  `HoteLDAP` varchar(50) DEFAULT NULL,
  `PortLDAP` int DEFAULT NULL,
  `VersionLDAP` int DEFAULT NULL,
  `SiteWeb` varchar(250) DEFAULT NULL,
  `DESTINATAIRE1` varchar(128) DEFAULT NULL,
  `DESTINATAIRE2` varchar(128) DEFAULT NULL,
  `EMAIL_GED` varchar(128) DEFAULT NULL,
  `DATE_MAJ_STRUCTURE` date DEFAULT NULL,
  `TAUX_TAXE` double DEFAULT NULL,
  `ControleBudget` bit(1) DEFAULT NULL,
  `oAuth` bit(1) DEFAULT NULL,
  `Forfait_taxi1` decimal(24,6) DEFAULT NULL,
  `Forfait_taxi2` decimal(24,6) DEFAULT NULL,
  `Forfait_taxi3` decimal(24,6) DEFAULT NULL,
  `FdaParCG` bit(1) DEFAULT NULL,
  PRIMARY KEY (`IDPARAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `PARTICIPANT` (
  `IDADHERANT` decimal(19,0) DEFAULT \'0\',
  `CODE_PARTICIPANT` int DEFAULT NULL,
  `IDPARTICIPANT` bigint NOT NULL AUTO_INCREMENT,
  `Adresse` text,
  `Date_Naissance` date DEFAULT NULL,
  `PRENOM` varchar(40) DEFAULT NULL,
  `NOM` varchar(60) DEFAULT NULL,
  `MATRICULE` varchar(20) DEFAULT NULL,
  `code_securite` varchar(255) DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `TEL` varchar(20) DEFAULT NULL,
  `NUMERO_PIECE_IDENTITE_PARTICIP` varchar(20) DEFAULT NULL,
  `SITUATION_MATRIMONIALE` int DEFAULT \'0\',
  `CONJOINTS` smallint DEFAULT \'0\',
  `ENFANTS` smallint DEFAULT \'0\',
  `FONCTION_PARTICIPANT` varchar(20) DEFAULT NULL,
  `SALAIRE` decimal(24,6) DEFAULT \'0.000000\',
  `PARACTIF` int DEFAULT \'0\',
  `TYPESALAIRE` int DEFAULT \'0\',
  `DATEDEPOT` date DEFAULT NULL,
  `DATE_IMMATRICULATION` date DEFAULT NULL,
  `BASESAL` decimal(24,6) DEFAULT \'0.000000\',
  `PHOTO` longblob,
  `S0CLEUNIK` int DEFAULT \'0\',
  `NOM_JEUNEFILLE` varchar(50) DEFAULT NULL,
  `SEXE` smallint DEFAULT \'0\',
  `IDAGENCE` int DEFAULT \'0\',
  `SOLDE` decimal(24,6) DEFAULT \'0.000000\',
  `NUMCOMPTE` varchar(50) DEFAULT NULL,
  `Lieu_Naissance` varchar(50) DEFAULT NULL,
  `CONGE` bit(1) DEFAULT b\'0\',
  `DEPART` bit(1) DEFAULT b\'0\',
  `SOLDEPREC` decimal(24,6) DEFAULT \'0.000000\',
  `NOMPREN` varchar(50) DEFAULT NULL,
  `IDClient` decimal(19,0) DEFAULT \'0\',
  `IDSite` decimal(19,0) DEFAULT \'0\',
  `Date_Affectation` date DEFAULT NULL,
  `Date_Entree` date DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `Enveille` bit(1) DEFAULT b\'0\',
  `Nature_Contrat` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDPARTICIPANT`),
  UNIQUE KEY `CODE_PARTICIPANT` (`CODE_PARTICIPANT`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `PHARMACI` (
  `PHCLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `NOMPHARM` varchar(50) DEFAULT NULL,
  `ADRPHARM` varchar(100) DEFAULT NULL,
  `CONTACTPHARM` varchar(20) DEFAULT NULL,
  `TELPHARM` varchar(20) DEFAULT NULL,
  `CODEPHARM` varchar(10) DEFAULT NULL,
  `COMPTE_COMPTABLE` varchar(8) DEFAULT NULL,
  `COMPTE_GENERAL` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`PHCLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `PRATICIE` (
  `PRCLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `CODEPRAT` int DEFAULT \'0\',
  `NOMPRAT` varchar(60) DEFAULT NULL,
  `ADRPRAT` varchar(100) DEFAULT NULL,
  `TELPRAT` varchar(10) DEFAULT NULL,
  `SPECIALITE` int DEFAULT \'0\',
  `CONTACT` varchar(20) DEFAULT NULL,
  `TELCONTACT` varchar(10) DEFAULT NULL,
  `SPCLEUNIK` int DEFAULT \'0\',
  `MONTACT` decimal(24,6) DEFAULT \'0.000000\',
  `DESACTE` varchar(150) DEFAULT NULL,
  `COMPTE_COMPTABLE` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`PRCLEUNIK`),
  UNIQUE KEY `CODEPRAT` (`CODEPRAT`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `REG_ADH` (
  `R0CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `DATEREG` date DEFAULT NULL,
  `MTREGLE` decimal(24,6) DEFAULT \'0.000000\',
  `MODEREGLEMENT` int DEFAULT \'0\',
  `REFREGLEMENT` varchar(30) DEFAULT NULL,
  `REFGLEMENT` varchar(30) DEFAULT NULL,
  `F1CLEUNIK` int DEFAULT \'0\',
  `IDBANQUE` decimal(19,0) DEFAULT \'0\',
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `heure` time DEFAULT NULL,
  `CODEBANQUE` varchar(50) DEFAULT NULL,
  `TIREUR` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`R0CLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `REG_PHA` (
  `R1CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `DATEREG` date DEFAULT NULL,
  `MTREGLE` decimal(24,6) DEFAULT \'0.000000\',
  `MODEREGLEMENT` int DEFAULT \'0\',
  `REFREGLEMENT` varchar(30) DEFAULT NULL,
  `FACLEUNIK` int DEFAULT \'0\',
  `IDBANQUE` decimal(19,0) DEFAULT \'0\',
  `heure` time DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `IDTRCHEQUE` decimal(19,0) DEFAULT \'0\',
  `CODEBANQUE` varchar(50) DEFAULT NULL,
  `TIREUR` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`R1CLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `REG_PRA` (
  `R2CLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `DATEREG` date DEFAULT NULL,
  `MTREGLE` decimal(24,6) DEFAULT \'0.000000\',
  `MODEREGLEMENT` int DEFAULT \'0\',
  `REFREGLEMENT` varchar(30) DEFAULT NULL,
  `F0CLEUNIK` int DEFAULT \'0\',
  `IDBANQUE` decimal(19,0) DEFAULT \'0\',
  `IDOPERATEUR` decimal(19,0) DEFAULT \'0\',
  `heure` time DEFAULT NULL,
  `IDTRCHEQUE` decimal(19,0) DEFAULT \'0\',
  `CODEBANQUE` varchar(50) DEFAULT NULL,
  `TIREUR` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`R2CLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `REGCOTIS` (
  `RECLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `DATEREG` date DEFAULT NULL,
  `COCLEUNIK` int DEFAULT \'0\',
  `MTREGLE` decimal(24,6) DEFAULT \'0.000000\',
  `REFGLEMENT` varchar(30) DEFAULT NULL,
  `MODEREGLEMENT` int DEFAULT \'0\',
  `IDBANQUE` decimal(19,0) DEFAULT \'0\',
  PRIMARY KEY (`RECLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `RUBDEP` (
  `IDRUBDEP` bigint NOT NULL AUTO_INCREMENT,
  `RUBRIQUE` varchar(50) DEFAULT NULL,
  `Compte` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDRUBDEP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `SETUP` (
  `SECLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `PLAFOND` decimal(24,6) DEFAULT \'0.000000\',
  `COTPLAFOND` decimal(24,6) DEFAULT \'0.000000\',
  `PLANCHER` decimal(24,6) DEFAULT \'0.000000\',
  `COTPLANCHER` decimal(24,6) DEFAULT \'0.000000\',
  `TAUX` double DEFAULT \'0\',
  `MAJORITE` smallint DEFAULT \'0\',
  `MTCOTISE` decimal(24,6) DEFAULT \'0.000000\',
  `DERNUM_COMMANDE` int DEFAULT \'0\',
  `MTCOTISECADRE` decimal(24,6) DEFAULT \'0.000000\',
  `COMPTEUR_ACHAT` int DEFAULT \'0\',
  `COMPTEUR_VENTE` int DEFAULT \'0\',
  `NOMIPM` varchar(50) DEFAULT NULL,
  `Adresse` text,
  `Email` varchar(256) DEFAULT NULL,
  `BP` varchar(50) DEFAULT NULL,
  `TEL` varchar(10) DEFAULT NULL,
  `CONTACT` varchar(50) DEFAULT NULL,
  `Email_Contact` varchar(256) DEFAULT NULL,
  `tel_contact` varchar(50) DEFAULT NULL,
  `oAuth` bit(1) DEFAULT b\'0\',
  `derNUM_depense` int DEFAULT \'0\',
  `dernum_pharmacie` int DEFAULT \'0\',
  `dernum_feuille` int DEFAULT \'0\',
  `dernum_facture` int DEFAULT \'0\',
  `dernum_TRCHEQUE` int DEFAULT \'0\',
  `dernum_LG` int DEFAULT \'0\',
  PRIMARY KEY (`SECLEUNIK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `SPECIALI` (
  `SPCLEUNIK` bigint NOT NULL AUTO_INCREMENT,
  `Specialite` varchar(50) DEFAULT NULL,
  `CodeSpecialite` varchar(10) DEFAULT NULL,
  `COMPTE_COMPTABLE` varchar(8) DEFAULT NULL,
  `DERNUM_PRATICIEN` int DEFAULT \'0\',
  PRIMARY KEY (`SPCLEUNIK`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `TRCHEQUE` (
  `IDTRCHEQUE` bigint NOT NULL AUTO_INCREMENT,
  `NUMTRCHEQUE` varchar(50) DEFAULT NULL,
  `PRCLEUNIK` int DEFAULT NULL,
  `PHCLEUNIK` int DEFAULT NULL,
  `MONTANT` decimal(24,6) DEFAULT NULL,
  `NUMCHEQUE` varchar(50) DEFAULT NULL,
  `IDBANQUE` decimal(19,0) DEFAULT NULL,
  `NBFACTURES` int DEFAULT NULL,
  `IDOPERATEUR` decimal(19,0) DEFAULT NULL,
  `idvalideur` int DEFAULT NULL,
  `TYPE` smallint DEFAULT NULL,
  `Date` date DEFAULT NULL,
  `heure` time DEFAULT NULL,
  `Date_validation` date DEFAULT NULL,
  `Validee` bit(1) DEFAULT NULL,
  PRIMARY KEY (`IDTRCHEQUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
            'CREATE TABLE IF NOT EXISTS `Type_Papier` (
  `IDType_Papier` bigint NOT NULL AUTO_INCREMENT,
  `Type_papier` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDType_Papier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        foreach ($statements as $sql) {
            DB::statement($sql);
        }
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $tables = [
            'AC_FEUIL', 'ADHERANT', 'BANQUE', 'CMDPHARM', 'CONGES', 'COT_PAR', 'COTISE',
            'DECOMPTE', 'DEPENSE', 'DOC_EXTERNES', 'DOC_PARTICIPANT', 'FACT_ADH', 'FACT_PHA',
            'FACT_PRA', 'FDA', 'FDD', 'FEUIL_MA', 'HISTORIQUE', 'LIGCMD', 'NUMEROTATION',
            'OPERATEUR', 'PARAM', 'PARTICIPANT', 'PHARMACI', 'PRATICIE', 'REG_ADH', 'REG_PHA',
            'REG_PRA', 'REGCOTIS', 'RUBDEP', 'SETUP', 'SPECIALI', 'TRCHEQUE', 'Type_Papier'
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        foreach ($tables as $table) {
            Schema::dropIfExists($table);
        }
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
};